<!--
    This is an example of some of the HTML I've worked with over the past 2-1/2 years, we've made great strides
    in moving our legacy application to utilize Bootstrap and be responsive and mobile compatible. The entire site can
    be seen at www.wmsolutions.com

    This specific segment is from our form builder application, answers from which are used to populate the PDF documents
    visible in the My Profiles section
!-->

<div class="row questionRow <?= $question->hasDependency() ? 'secondary-level' : '' ?>" <?= $question->getRowAttributes() ?>>
    <div class="float-none col-xs-12 col-md-10 col-lg-9"><hr /></div>
    <div class="col-xs-12 col-sm-5 col-md-4 col-lg-3">
        <label><?= $question->getLabel() ?></label>
    </div>
    <div class="col-xs-12 col-sm-5 col-md-4 col-lg-3">
        <?= $this->formText(
            $question->getId(),
            $answer->getUserAnswerBody(),
            $answer->getInputAttributes(
                [
                    'class' => 'form-control'
                ]
            )
        ) ?>
    </div>
</div>